export const TIME_UNITS = {
  MILLISECOND: 1,
  SECOND: 1000,
  MINUTE: 1000 * 60,
  HOUR: 1000 * 60 * 60,
  DAY: 1000 * 60 * 60 * 24,
  WEEK: 1000 * 60 * 60 * 24 * 7,
  MONTH_30: 1000 * 60 * 60 * 24 * 30, // Approximate
  YEAR_365: 1000 * 60 * 60 * 24 * 365, // Non leap year
} as const;

export const TTL = {
  SECOND: TIME_UNITS.SECOND,
  MINUTE: TIME_UNITS.MINUTE,
  HOUR: TIME_UNITS.HOUR,
  DAY: TIME_UNITS.DAY,
  WEEK: TIME_UNITS.WEEK,
  MONTH: TIME_UNITS.MONTH_30,
  YEAR: TIME_UNITS.YEAR_365,

  FIVE_MINUTES: 5 * TIME_UNITS.MINUTE,
  FIFTEEN_MINUTES: 15 * TIME_UNITS.MINUTE,
  THIRTY_MINUTES: 30 * TIME_UNITS.MINUTE,
  ONE_HOUR: TIME_UNITS.HOUR,
  TWO_HOURS: 2 * TIME_UNITS.HOUR,
  FOUR_HOURS: 4 * TIME_UNITS.HOUR,
  EIGHT_HOURS: 8 * TIME_UNITS.HOUR,
  TWELVE_HOURS: 12 * TIME_UNITS.HOUR,
  ONE_DAY: TIME_UNITS.DAY,
  TWO_DAYS: 2 * TIME_UNITS.DAY,
  ONE_WEEK: TIME_UNITS.WEEK,
  TWO_WEEKS: 2 * TIME_UNITS.WEEK,
  THIRTY_DAYS: 30 * TIME_UNITS.DAY,

  THREE_MONTHS: 3 * TIME_UNITS.MONTH_30,
  SIX_MONTHS: 6 * TIME_UNITS.MONTH_30,
  ONE_YEAR: TIME_UNITS.YEAR_365,
} as const;
